name: Build Android APK (Tauri 2.x)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Clean environment
        run: |
          rm -rf Genshin-Impact-Wish-Simulator/src-tauri
          mkdir -p Genshin-Impact-Wish-Simulator/src-tauri

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Tauri CLI
        run: npm install -g @tauri-apps/cli@next

      - name: Create correct config
        run: |
          cat << 'EOF' > Genshin-Impact-Wish-Simulator/src-tauri/tauri.conf.json
          {
            "$schema": "../node_modules/@tauri-apps/cli/schema.json",
            "productName": "genshin-impact",
            "version": "0.1.0",
            "build": {
              "distDir": "../dist",
              "devPath": "http://localhost:8080"
            },
            "app": {
              "bundleIdentifier": "com.example.genshinimpact"
            }
          }
          EOF

          # 验证配置文件
          echo "生成的配置文件内容："
          cat Genshin-Impact-Wish-Simulator/src-tauri/tauri.conf.json

      - name: Init Android
        run: |
          cd Genshin-Impact-Wish-Simulator
          tauri android init --ci

      - name: Build APK
        run: |
          cd Genshin-Impact-Wish-Simulator
          tauri android build --debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: genshin-impact-apk
          path: Genshin-Impact-Wish-Simulator/src-tauri/target/android/debug/*.apk