name: Build Android APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Clean existing config
        run: |
          rm -rf Genshin-Impact-Wish-Simulator/src-tauri/tauri.conf.json*
          mkdir -p Genshin-Impact-Wish-Simulator/src-tauri/icons

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install
        working-directory: Genshin-Impact-Wish-Simulator

      - name: Force Install Tauri CLI 1.x
        run: npm install -g @tauri-apps/cli@latest

      - name: Generate Config
        run: |
          CONFIG_FILE="Genshin-Impact-Wish-Simulator/src-tauri/tauri.conf.json"
          echo '{
            "build": {
              "distDir": "../dist",
              "devPath": "http://localhost:8080"
            },
            "package": {
              "productName": "genshin-impact",
              "version": "0.1.0"
            },
            "tauri": {
              "bundle": {
                "identifier": "com.example.genshinimpact",
                "icon": ["icons/32x32.png", "icons/128x128.png"]
              },
              "allowlist": {
                "all": true
              }
            }
          }' > $CONFIG_FILE
          
          # 确保图标文件存在（创建空文件作为后备）
          touch Genshin-Impact-Wish-Simulator/src-tauri/icons/{32x32.png,128x128.png}
          echo "Generated config:"
          cat $CONFIG_FILE

      - name: Init Tauri Android
        run: |
          cd Genshin-Impact-Wish-Simulator
          tauri android init
          echo "Init completed"

      - name: Build APK
        run: |
          cd Genshin-Impact-Wish-Simulator
          tauri android build --debug
          ls -la src-tauri/target/android/debug/

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: genshin-impact-apk
          path: Genshin-Impact-Wish-Simulator/src-tauri/target/android/debug/*.apk