name: Build Android APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Detect Tauri version
        id: detect-tauri
        run: |
          if grep -q '"@tauri-apps/cli": "2' package.json; then
            echo "TAURI_VERSION=2" >> $GITHUB_ENV
          elif grep -q '"@tauri-apps/cli": "^1' package.json; then
            echo "TAURI_VERSION=1" >> $GITHUB_ENV
          else
            echo "TAURI_VERSION=1" >> $GITHUB_ENV
          fi
          echo "Detected Tauri $TAURI_VERSION.x"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install
        working-directory: Genshin-Impact-Wish-Simulator

      - name: Install Tauri CLI
        run: |
          if [ "$TAURI_VERSION" = "2" ]; then
            npm install -g @tauri-apps/cli@next
          else
            npm install -g @tauri-apps/cli@latest
          fi

      - name: Prepare Tauri config
        run: |
          chmod +x ./prepare-tauri-config.sh
          ./prepare-tauri-config.sh
        working-directory: Genshin-Impact-Wish-Simulator
        env:
          TAURI_VERSION: ${{ env.TAURI_VERSION }}

      - name: Init Tauri Android
        run: |
          rm -rf src-tauri/target
          tauri android init
        working-directory: Genshin-Impact-Wish-Simulator

      - name: Build APK
        run: tauri android build --debug
        working-directory: Genshin-Impact-Wish-Simulator

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: genshin-impact-apk
          path: Genshin-Impact-Wish-Simulator/src-tauri/target/android/debug/*.apk