name: Build Android APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      # 1. 检出代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. 进入项目子目录
      - name: Navigate to project
        run: cd Genshin-Impact-Wish-Simulator && ls -la
        shell: bash

      # 3. 设置 Java 环境
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # 4. 安装 Android 环境
      - name: Install Android SDK
        uses: android-actions/setup-android@v3
        with:
          ndk-version: '25.1.8937393'  # 指定 NDK 版本

      # 5. 设置 Rust 工具链
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: aarch64-linux-android
          override: true

      # 6. 设置 Node.js
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # 7. 安装依赖
      - name: Install dependencies
        run: |
          npm install
          npm install @tauri-apps/cli@latest
        working-directory: Genshin-Impact-Wish-Simulator

      # 8. 初始化 Tauri Android
      - name: Init Tauri Android
        run: |
          rm -rf src-tauri/target  # 清理旧构建
          tauri android init
        working-directory: Genshin-Impact-Wish-Simulator
        env:
          ANDROID_HOME: ${{ env.ANDROID_SDK_ROOT }}
          NDK_HOME: ${{ env.ANDROID_NDK_ROOT }}

      # 9. 构建 APK
      - name: Build APK (Debug)
        run: tauri android build --debug
        working-directory: Genshin-Impact-Wish-Simulator
        env:
          ANDROID_HOME: ${{ env.ANDROID_SDK_ROOT }}
          NDK_HOME: ${{ env.ANDROID_NDK_ROOT }}

      # 10. 上传 APK
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: genshin-impact-debug
          path: Genshin-Impact-Wish-Simulator/src-tauri/target/android/debug/*.apk