name: Build Android APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      # 1. 检出代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. 进入项目子目录（关键修复）
      - name: Navigate to project folder
        run: cd Genshin-Impact-Wish-Simulator && ls -la
        shell: bash

      # 3. 设置 Java 环境
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # 4. 设置 Android 环境
      - name: Install Android SDK
        uses: android-actions/setup-android@v3

      # 5. 设置 Rust 环境（注意目标架构）
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: aarch64-linux-android  # ARM64 设备
          override: true

      # 6. 设置 Node.js
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # 7. 安装依赖（现在会在子目录中运行）
      - name: Install dependencies
        run: npm install
        working-directory: Genshin-Impact-Wish-Simulator

      # 8. 安装 Tauri CLI
      - name: Install Tauri CLI
        run: npm install -g @tauri-apps/cli

      # 9. 构建 Android APK
      - name: Build Android APK
        run: tauri android build --debug
        working-directory: Genshin-Impact-Wish-Simulator
        env:
          ANDROID_HOME: ${{ env.ANDROID_SDK_ROOT }}
          NDK_HOME: ${{ env.ANDROID_NDK_ROOT }}

      # 10. 上传 APK
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-debug-apk
          path: Genshin-Impact-Wish-Simulator/src-tauri/target/android/debug/*.apk